
const seventeenSeriesGradList = [
    { sn: 1, name: "ONUOHA, EBUKA CHINEMEREM", regNumber: "16/SC/CH/484", classification: "SECOND CLASS (LOWER DIVISION)", sex: "M" },
    { sn: 2, name: "NSUBONG, INIMFON MICHAEL", regNumber: "16/SC/CH/486", classification: "SECOND CLASS (LOWER DIVISION)", sex: "M" },
    { sn: 3, name: "ESSANG, DANIEL EDET", regNumber: "16/SC/CH/488", classification: "SECOND CLASS (LOWER DIVISION)", sex: "M" },
    { sn: 4, name: "UZOEWULU, MARYLILIAN OGONNA", regNumber: "16/SC/CH/491", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 5, name: "OMALU, IFUNANYA JULIET", regNumber: "16/SC/CH/492", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 6, name: "ARCHIBONG, MFON VINCENT", regNumber: "16/SC/CH/494", classification: "SECOND CLASS (LOWER DIVISION)", sex: "M" },
    { sn: 7, name: "NJOKU, KINGSLEY AJUZIE", regNumber: "16/SC/CH/495", classification: "SECOND CLASS (LOWER DIVISION)", sex: "M" },
    { sn: 8, name: "AZUBUIKE, AMANDA CHIAMAKA", regNumber: "16/SC/CH/497", classification: "SECOND CLASS (UPPER DIVISION)", sex: "F" },
    { sn: 9, name: "SAMUEL, SAMUEL", regNumber: "16/SC/CH/501", classification: "SECOND CLASS (LOWER DIVISION)", sex: "M" },
    { sn: 10, name: "SLYVESTER, LUCY JACKSON", regNumber: "16/SC/CH/503", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 11, name: "INYANG, BLESSED PAUL", regNumber: "16/SC/CH/509", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 12, name: "NWAUBAN, UGWUEZE GOODLUCK", regNumber: "16/SC/CH/513", classification: "SECOND CLASS (LOWER DIVISION)", sex: "M" },
    { sn: 13, name: "OBAIKA, RITA OSEIMELU", regNumber: "16/SC/CH/517", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 14, name: "ETUK, ELIAS-ITOHOWO SUNNY", regNumber: "16/SC/CH/518", classification: "SECOND CLASS (LOWER DIVISION)", sex: "M" },
    { sn: 15, name: "STEPHEN, SIFONABASI USORO", regNumber: "16/SC/CH/526", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 16, name: "ANYANWU, ASSUMPTA C.", regNumber: "16/SC/CH/527", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 17, name: "EFIE, ENAMIDEM ASUQUO", regNumber: "16/SC/CH/528", classification: "THIRD CLASS", sex: "F" },
    { sn: 18, name: "NOAH EDIDIONG KURE-ABASI", regNumber: "16/SC/CH/530", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 19, name: "SAM, JOSEPH PIUS", regNumber: "16/SC/CH/531", classification: "SECOND CLASS (LOWER DIVISION)", sex: "M" },
    { sn: 20, name: "OBONG, EDIDIONG OBONG", regNumber: "16/SC/CH/536", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 21, name: "AMAH, DEBORAH SUNDAY", regNumber: "16/SC/CH/539", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 22, name: "UDO, IMOBONG JOSEPH", regNumber: "16/SC/CH/540", classification: "SECOND CLASS (UPPER DIVISION)", sex: "F" },
    { sn: 23, name: "IKOTT, MARY ETIM", regNumber: "16/SC/CH/544", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 24, name: "JEREMIAH, PEASE EKWERE", regNumber: "16/SC/CH/547", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 25, name: "UDO, IDONGESIT WILLIAM", regNumber: "16/SC/CH/554", classification: "SECOND CLASS (UPPER DIVISION)", sex: "M" },
    { sn: 26, name: "UKO, IFEOMA", regNumber: "16/SC/CH/562", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 27, name: "IBANGA, CAROLINE IDARA", regNumber: "16/SC/CH/565", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 28, name: "TIM, PATIENCE SOLOMON", regNumber: "16/SC/CH/568", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 29, name: "EKENNA, NZUBECHI JANE", regNumber: "16/SC/CH/570", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 30, name: "OKON, FELIX EFFIONG", regNumber: "16/SC/CH/573", classification: "SECOND CLASS (LOWER DIVISION)", sex: "M" },
    { sn: 31, name: "ASUQUO, EMMANUEL OKON", regNumber: "16/SC/CH/504", classification: "SECOND CLASS (LOWER DIVISION)", sex: "M" },
    { sn: 32, name: "EFFIONG, EUNICE EDEM", regNumber: "17/SC/CH/582", classification: "SECOND CLASS (UPPER DIVISION)", sex: "F" },
    { sn: 33, name: "OKON, ITORO JOSEPH", regNumber: "17/SC/CH/584", classification: "SECOND CLASS (LOWER DIVISION)", sex: "M" },
    { sn: 34, name: "OWAN, MARTIN BASSEY", regNumber: "17/SC/CH/589", classification: "SECOND CLASS (LOWER DIVISION)", sex: "M" },
    { sn: 35, name: "SUNDAY, SOLOMON UKPONOBONG", regNumber: "17/SC/CH/601", classification: "SECOND CLASS (UPPER DIVISION)", sex: "M" },
    { sn: 36, name: "NNAMANI, MATHEW RAPHAEL", regNumber: "17/SC/CH/603", classification: "SECOND CLASS (UPPER DIVISION)", sex: "M" },
    { sn: 37, name: "JOHN, ONYEKACHI GREAT", regNumber: "17/SC/CH/608", classification: "SECOND CLASS (UPPER DIVISION)", sex: "M" },
    { sn: 38, name: "INILLIE, MOSES MONDAY", regNumber: "17/SC/CH/613", classification: "SECOND CLASS (UPPER DIVISION)", sex: "M" },
    { sn: 39, name: "NTIA, ESTHER SYLVERSTER", regNumber: "17/SC/CH/614", classification: "SECOND CLASS (UPPER DIVISION)", sex: "F" },
    { sn: 40, name: "NATHAN, ANIEFIOK OKON", regNumber: "17/SC/CH/620", classification: "SECOND CLASS (UPPER DIVISION)", sex: "F" },
    { sn: 41, name: "UGWU, ANGELA NKIRU", regNumber: "17/SC/CH/621", classification: "SECOND CLASS (UPPER DIVISION)", sex: "F" },
    { sn: 42, name: "UWEM, ELIJAH SAMSON", regNumber: "17/SC/CH/622", classification: "SECOND CLASS (UPPER DIVISION)", sex: "M" },
    { sn: 43, name: "EMMANUEL, JOY INIMBOM", regNumber: "17/SC/CH/623", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 44, name: "ADIELE, PRECIOUS CHIMA", regNumber: "17/SC/CH/624", classification: "FIRST CLASS", sex: "F" },
    { sn: 45, name: "BENEDICT, PAUL NSEYO", regNumber: "17/SC/CH/640", classification: "SECOND CLASS (UPPER DIVISION)", sex: "M" },
    { sn: 46, name: "UBOKUDOM, UWANA", regNumber: "17/SC/CH/641", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" },
    { sn: 47, name: "BASSEY, BLESSED SAMUEL", regNumber: "17/SC/CH/654", classification: "SECOND CLASS (UPPER DIVISION)", sex: "M" },
    { sn: 48, name: "NWOSU, TOCHUKWU VIVIAN", regNumber: "17/SC/CH/667", classification: "SECOND CLASS (UPPER DIVISION)", sex: "F" },
    { sn: 49, name: "EYO, FAITH INI", regNumber: "17/SC/CH/676", classification: "SECOND CLASS (UPPER DIVISION)", sex: "F" },
    { sn: 50, name: "PATRICK, GIFT AMBROSE", regNumber: "17/SC/CH/677", classification: "SECOND CLASS (UPPER DIVISION)", sex: "F" },
    { sn: 51, name: "UDOKA, JUSTINE EMMANUEL", regNumber: "17/SC/CH/766", classification: "SECOND CLASS (UPPER DIVISION)", sex: "M" },
    { sn: 52, name: "AKPAN, EKEMINIABASI MONDAY", regNumber: "17/SC/CH/777", classification: "SECOND CLASS (UPPER DIVISION)", sex: "F" },
    { sn: 53, name: "ELEKE, PRECIOUS OLUCHUKWU", regNumber: "17/SC/CH/794", classification: "SECOND CLASS (LOWER DIVISION)", sex: "F" }
]


const eighteenSeriesGradList = [
    { sn: 1, regNumber: "18/SC/CH/693", name: "AKPABIO, FAVOUR IDARA", sex: "F", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 2, regNumber: "18/SC/CH/694", name: "OTIMANAM, PEARL HILARY", sex: "F", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 3, regNumber: "18/SC/CH/695", name: "ESSIEN, ETIMA MICHAEL", sex: "F", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 4, regNumber: "18/SC/CH/699", name: "UJOR, FAVOUR ANGELA", sex: "F", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 5, regNumber: "18/SC/CH/700", name: "EDEKE, IVY EDEKE", sex: "F", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 6, regNumber: "18/SC/CH/701", name: "ASUQUO, JOSEPH EKONG", sex: "M", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 7, regNumber: "18/SC/CH/704", name: "JACOB, KUBIAT INUKINYANG", sex: "F", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 8, regNumber: "18/SC/CH/707", name: "ETIM INYENE MICHAEL", sex: "M", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 9, regNumber: "18/SC/CH/711", name: "NELSON, SHARON INEMESIT", sex: "F", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 10, regNumber: "18/SC/CH/715", name: "AWAK, MBUOTIDEM SUNDAY", sex: "F", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 11, regNumber: "18/SC/CH/718", name: "IKOTINYIE, LYDIA GODWIN", sex: "F", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 12, regNumber: "18/SC/CH/722", name: "EYO, ABASIENYENE EMMANUEL", sex: "F", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 13, regNumber: "18/SC/CH/725", name: "USEN, EZEKIEL MONDAY", sex: "M", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 14, regNumber: "18/SC/CH/726", name: "UDO, ETEBONG EFFIONG", sex: "M", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 15, regNumber: "18/SC/CH/727", name: "JOHN, BELIEVE OFFIONG", sex: "M", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 16, regNumber: "18/SC/CH/728", name: "OKON, INIUBONG UMANA", sex: "M", classification: "FIRST CLASS" },
    { sn: 17, regNumber: "18/SC/CH/730", name: "MICHAEL, ABASI-IFREKE JOSEPH", sex: "F", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 18, regNumber: "18/SC/CH/731", name: "ONYONG, EMMANUEL EVENTUS", sex: "M", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 19, regNumber: "18/SC/CH/732", name: "EMMANUEL, JOSEPHINE JOHN", sex: "F", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 20, regNumber: "18/SC/CH/735", name: "NDAH, EPHRAIM ANIEFIOK", sex: "M", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 21, regNumber: "18/SC/CH/736", name: "UWAK-MFON, CYRIL PRINCE", sex: "M", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 22, regNumber: "18/SC/CH/737", name: "JAMES RUTH MOFFAT", sex: "F", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 23, regNumber: "18/SC/CH/740", name: "JAMES MFONISO UDOFOT", sex: "M", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 24, regNumber: "18/SC/CH/742", name: "EFFIONG, ESTHER MICHAEL", sex: "F", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 25, regNumber: "18/SC/CH/743", name: "MOFFAT, LUCY EFFIONG", sex: "F", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 26, regNumber: "18/SC/CH/744", name: "EMMAUEL, SAVIOUR ELISHA", sex: "M", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 27, regNumber: "18/SC/CH/745", name: "OKONNAH, VICTORIA IMAOBONG", sex: "F", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 28, regNumber: "18/SC/CH/751", name: "JIMBO, ESTHER ETIM", sex: "F", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 29, regNumber: "18/SC/CH/764", name: "ESSIEN, NATHANIEL SAMUEL", sex: "M", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 30, regNumber: "18/SC/CH/770", name: "MFONIMA, KUTMFON IFURE", sex: "F", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 31, regNumber: "18/SC/CH/781", name: "AKPASO, EFIOK EFIOK", sex: "M", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 32, regNumber: "18/SC/CH/797", name: "ONWEGNA, OGECHI", sex: "F", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 33, regNumber: "18/SC/CH/800", name: "UMOREN, OBONG-OFIOK SUNDAY", sex: "F", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 34, regNumber: "18/SC/CH/802", name: "EDET, VICTORIA VICTOR", sex: "F", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 35, regNumber: "18/SC/CH/803", name: "AKPAN, BLESSING ANTHONY", sex: "F", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 36, regNumber: "19/SC/CH/836", name: "IBUOT, ITORO-OBONG EFFIONG", sex: "M", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 37, regNumber: "19/SC/CH/845", name: "JACOB, ITORO ITA", sex: "F", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 38, regNumber: "19/SC/CH/848", name: "UNAAM, UKEMEABASI JACOB", sex: "F", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 39, regNumber: "19/SC/CH/899", name: "AMADI, IFEOMA BLESSING", sex: "F", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 40, regNumber: "19/SC/CH/905", name: "OKON, VICTORIA FRIDAY", sex: "F", classification: "SECOND CLASS (LOWER DIVISION)" },
    { sn: 41, regNumber: "19/SC/CH/908", name: "UDOEKPO, NDIFREKE REBEKAH", sex: "F", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 42, regNumber: "19/SC/CH/912", name: "JOHN, JUSTINA ETEBONG", sex: "F", classification: "SECOND CLASS (UPPER DIVISION)" },
    { sn: 43, regNumber: "19/SC/CH/913", name: "ASUKWO, HONOUR OSCAR", sex: "F", classification: "SECOND CLASS (UPPER DIVISION)" }
]

export { seventeenSeriesGradList, eighteenSeriesGradList }