export const mscCourseThreeToSix = [
  {
    code: "CHM755",
    title: "Seminar",
    credit_hrs: 3,
    prerequisite: "",
    semester: "three",
    desc: "",
  },
  {
    code: "CHM756",
    title: "Thesis",
    credit_hrs: 12,
    prerequisite: "",
    semester: "three",
    desc: "",
  },
];

// Analytical Chemistry
export const analyticalMscCourseOne = [
  {
    code: "CHM711",
    title: "Advanced Research Methodology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM712",
    title: "Chemistry of Life Processes",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM713",
    title: "Advances in Analytical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM714",
    title: "Air, and Soil Analyses",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM715",
    title: "Food and Water Analysis Elective",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM716*",
    title: "Environmental Economics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM717*",
    title: "Application of Geochemical Technology in Petroleum Exploration",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM718*",
    title: "Advanced Mineral Processing and Metallurgy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];

export const analyticalMscCourseTwo = [
  {
    code: "CHM721",
    title: "Quality Assurance of Chemical Products/Products Export Criteria",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM722",
    title: " Electronics and Instrumentation",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM723",
    title: "Forensic Chemistry and Toxicology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM724",
    title: "Process Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM725",
    title: "Advanced Theoretical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM726*",
    title: "Textile and Colour Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM727*",
    title: "Advanced Wood Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

// Environmental Chemistry
export const environmentalMscCourseOne = [
  {
    code: "CHM711",
    title: "Advanced Research Methodology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM712",
    title: "Chemistry of Life Processes",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "CHM714",
    title: "Air, and Soil Analyses",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM715",
    title: "Food and Water Analysis Elective",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM719",
    title: "Organic Photochemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM716*",
    title: "Environmental Economics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM717*",
    title: "Application of Geochemical Technology in Petroleum Exploration",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM718*",
    title: "Advanced Mineral Processing and Metallurgy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];
export const environmentalMscCourseTwo = [
  {
    code: "CHM721",
    title: "Quality Assurance of Chemical Products/Products Export Criteria",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM722",
    title: "Electronics and Instrumentation",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM728",
    title: "Advances in Energy Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM729",
    title: "Advances in Pollution Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM725*",
    title: "Advances in Theoretical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM726*",
    title: "Textile and Colour Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM727*",
    title: "Advanced Wood Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

//  Industrial Chemistry
export const industrialMscCourseOne = [
  {
    code: "CHM711",
    title: "Advanced Research Methodology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM712",
    title: "Chemistry of Life Processes",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "CHM731",
    title: "Food Chemistry and Technology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM732",
    title: "Process Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM719",
    title: "Organic Photochemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM716*",
    title: "Environmental Economics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM718*",
    title: "Advanced Mineral Processing and Metallurgy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM733*",
    title: "Advanced Paper Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];
export const industrialMscCourseTwo = [
  {
    code: "CHM721",
    title: "Quality Assurance of Chemical Products/Products Export Criteria",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM722",
    title: "Electronics and Instrumentation",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM724",
    title: "Advances in Industrial Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM729",
    title: "Advances in Pollution Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM725*",
    title: "Advances in Theoretical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM726*",
    title: "Textile and Colour Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM727*",
    title: "Advanced Wood Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

//  Inorganic Chemistry
export const inorganicMscCourseOne = [
  {
    code: "CHM711",
    title: "Advanced Research Methodology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM712",
    title: "Chemistry of Life Processes",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "CHM734",
    title: "Molecular Polyhedral Compounds",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM735",
    title: "Advancement in Coordination Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM736",
    title: "Medicinal Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM716*",
    title: "Environmental Economics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM717*",
    title: "Application of Geochemical Technology in Petroleum Exploration",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM718*",
    title: "Advanced Mineral Processing and Metallurgy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];
export const inorganicMscCourseTwo = [
  {
    code: "CHM722",
    title: "Electronics and Instrumentation",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM741",
    title: "Advanced Chemistry of Inner Transition Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM742",
    title: "Special Topics in Inorganic Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM743",
    title: "Homogeneous and Heterogeneous Catalysis",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM725*",
    title: "Advances in Theoretical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM726*",
    title: "Textile and Colour Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM727*",
    title: "Advanced Wood Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

//  Organic Chemistry
export const organicMscCourseOne = [
  {
    code: "CHM711",
    title: "Advanced Research Methodology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM712",
    title: "Chemistry of Life Processes",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "CHM736",
    title: "Medicinal Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM737",
    title: "Advanced Organic Spectroscopy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM719",
    title: "Organic Photochemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM716*",
    title: "Environmental Economics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM717*",
    title: "Application of Geochemical Technology in Petroleum Exploration",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM718*",
    title: "Advanced Mineral Processing and Metallurgy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];

export const organicMscCourseTwo = [
  {
    code: "CHM722",
    title: "Electronics and Instrumentation",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM744",
    title: "Bioorganic Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM745",
    title: "Industrial Organic Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },

  {
    code: "CHM746",
    title: "Drug Discovery and Development",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM725*",
    title: "Advances in Theoretical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM726*",
    title: "Textile and Colour Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM727*",
    title: "Advanced Wood Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

//  Physical Chemistry
export const physicalMscCourseOne = [
  {
    code: "CHM711",
    title: "Advanced Research Methodology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM712",
    title: "Chemistry of Life Processes",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "CHM738",
    title:
      "Advances in Electro-Catalysis/Semi Conducting Oxides and Nano-Materials",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM739",
    title: "Advances in Chemical Thermodynamics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM751",
    title: "Biophysical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM716*",
    title: "Environmental Economics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM717*",
    title: "Application of Geochemical Technology in Petroleum Exploration",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM718*",
    title: "Advanced Mineral Processing and Metallurgy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];

export const physicalMscCourseTwo = [
  {
    code: "CHM721",
    title: "Quality Assurance of Chemical Products/Products Export Criteria",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM722",
    title: "Electronics and Instrumentation",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM747",
    title: "Advances in Electrochemistry and Electrochemical Technology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM748",
    title:
      "Advances in Stress Corrosion/Hydrogen Embrittlement in Petroleum Industry etc",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM725*",
    title: "Advanced Theoretical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM726*",
    title: "Textile and Colour Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM727*",
    title: "Advanced Wood Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

//  Polymer Chemistry
export const polymerMscCourseOne = [
  {
    code: "CHM711",
    title: "Advanced Research Methodology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM712",
    title: "Chemistry of Life Processes",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "CHM752",
    title: "Advanced Polymer Synthesis",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM753",
    title: "Plastic Equipment and Plant Design",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM754",
    title: "Advanced Polymer Processing Technology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM716*",
    title: "Environmental Economics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM717*",
    title: "Application of Geochemical Technology in Petroleum Exploration",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM718*",
    title: "Advanced Mineral Processing and Metallurgy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];

export const polymerMscCourseTwo = [
  {
    code: "CHM722",
    title: "Electronics and Instrumentation",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM749",
    title: "Polymer Reactor Engineering",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM761",
    title: "Solid State Properties of Polymer",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },

  {
    code: "CHM762",
    title: "Polymer Rheology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM725*",
    title: "Advanced Theoretical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM726*",
    title: "Textile and Colour Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM733*",
    title: "Advanced Paper Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];
