export const mscCourseThreeToSix = [
  {
    code: "CHM631",
    title: "Seminar",
    credit_hrs: 3,
    prerequisite: "",
    semester: "third",
    desc: "",
  },
  {
    code: "CHM656",
    title: "Dissertation",
    credit_hrs: 6,
    prerequisite: "",
    semester: "third",
    desc: "",
  },
];

// Analytical Chemistry
export const analyticalMscCourseOne = [
  {
    code: "CHM611",
    title: "Separation Techniques",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM612",
    title: "Computational Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM613",
    title:
      "Spectroscopic Methods in Structure Determination and Chemical Analysis",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM614",
    title: "Biochemical and Pharmaceutical Methods of Analysis",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM615",
    title: "Radiochemical Methods of Analysis",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "SCI611",
    title: "Management and Entrepreneurship",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "SCI612",
    title: "ICT and Research Methodology",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];

export const analyticalMscCourseTwo = [
  {
    code: "CHM621",
    title: "Thermal and Photochemical Methods of Analysis",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM622",
    title: "Petroleum Geochemistry and Analysis of Petroleum Products",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM623",
    title: "Advanced Classical Analysis",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM624",
    title: "Electroanalytical Methods of Analysis",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "SCI621",
    title: "Science, Environment and Innovation",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

// Environmental Chemistry
export const environmentalMscCourseOne = [
  {
    code: "CHM611",
    title: "Separation Techniques",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM612",
    title: "Computational Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM613",
    title:
      "Spectroscopic Methods in Structure Determination and Chemical Analysis",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "CHM616",
    title: "Chemistry of the Biosphere",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM617",
    title: "Environmental Toxicology and Analysis",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "SCI611",
    title: "Management and Entrepreneurship",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "SCI612",
    title: "ICT and Research Methodology",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];
export const environmentalMscCourseTwo = [
  {
    code: "CHM625",
    title: "Environmental Impact Assessment and Pollution Control",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM626",
    title: "Chemistry of the Atmosphere",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM627",
    title: "Chemistry of the Hydrosphere",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM628",
    title: "Chemistry of Waste and Waste Transformation",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "SCI621",
    title: "Science, Environment and Innovation",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

//  Industrial Chemistry
export const industrialMscCourseOne = [
  {
    code: "CHM611",
    title: "Separation Techniques",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM612",
    title: "Computational Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM613",
    title:
      "Spectroscopic Methods in Structure Determination and Chemical Analysis",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "CHM618",
    title: "Advanced Industrial Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM619",
    title: "Industrial Inorganic Chemicals",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "SCI611",
    title: "Management and Entrepreneurship",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "SCI612",
    title: "ICT and Research Methodology",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM633*",
    title: "Advanced Paper Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];
export const industrialMscCourseTwo = [
  {
    code: "CHM668",
    title: "Polymer Synthesis/Laboratory",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM629",
    title: "Formulation Chemistry",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM641",
    title: "Wood/Paper Chemistry and Technology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM642",
    title: "Petroleum Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "SCI621",
    title: "Science, Environment and Innovation",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

//  Inorganic Chemistry
export const inorganicMscCourseOne = [
  {
    code: "CHM611",
    title: "Separation Techniques",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM612",
    title: "Computational Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM613",
    title: "Spectroscopic Methods in Structure Determination and Chemical",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM633",
    title: "Inorganic Reactions Mechanism",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM634",
    title: "Non Aqueous Solvents",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "SCI611",
    title: "Management and Entrepreneurship",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "SCI612",
    title: "ICT and Research Methodology",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];
export const inorganicMscCourseTwo = [
  {
    code: "CHM643",
    title: "Advanced Coordination Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM644",
    title: "Bonding in Non-transition Elements",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM645",
    title: "Advance Organometallic Chemistry",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM646",
    title: "Bioinorganic Chemistry",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM647",
    title: "Nuclear and Radiochemistry",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "SCI621",
    title: "Science, Environment and Innovation",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

//  Organic Chemistry
export const organicMscCourseOne = [
  {
    code: "CHM611",
    title: "Separation Techniques",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM612",
    title: "Computational Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM613",
    title: "Spectroscopic Methods in Structure Determination and Chemical",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM635",
    title: "Heterocyclic Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM636",
    title: "Organic Synthesis I",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "SCI611",
    title: "Management and Entrepreneurship",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "SCI612",
    title: "ICT and Research Methodology",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];
export const organicMscCourseTwo = [
  {
    code: "CHM645",
    title: "Advanced Organometallic Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM648",
    title: "Organic Reaction Mechanism",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM649",
    title: "Organic Synthesis II",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },

  {
    code: "CHM662",
    title: "Carbohydrate and Nucleic Acids",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "SCI621",
    title: "Science, Environment and Innovation",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

//  Physical Chemistry
export const physicalMscCourseOne = [
  {
    code: "CHM611",
    title: "Separation Techniques",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM612",
    title: "Computational Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM613",
    title: "Spectroscopic Methods in Structure Determination and Chemical",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM637",
    title: "Advanced Chemical Kinetics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM638",
    title: "Advanced Statistical Thermodynamics",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "SCI611",
    title: "Management and Entrepreneurship",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "SCI612",
    title: "ICT and Research Methodology",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];

export const physicalMscCourseTwo = [
  {
    code: "CHM6631",
    title: "Materials Chemistry and Utilization",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM664",
    title: "Advanced Thermodynamics",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM665",
    title: "Special Topics in Surface and Colloidal Chemistry",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM666",
    title: "Advanced Quantum Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "SCI621",
    title: "Science, Environment and Innovation",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

//  Polymer Chemistry
export const polymerMscCourseOne = [
  {
    code: "CHM611",
    title: "Separation Techniques",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM612",
    title: "Computational Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM613",
    title: "Spectroscopic Methods in Structure Determination and Chemical",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM639",
    title: "Polymer Process Technology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM651",
    title: "Polymer Structure",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "SCI611",
    title: "Management and Entrepreneurship",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "SCI612",
    title: "ICT and Research Methodology",
    credit_hrs: 2,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];

export const polymerMscCourseTwo = [
  {
    code: "CHM667",
    title: "Polymer Materials and Characterization Techniques",
    credit_hrs: 4,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM669",
    title: "Polymer Synthesis and Laboratory",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM681",
    title: "Polymer Solution and Reactions",
    credit_hrs: 4,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "SCI621",
    title: "Science, Environment and Innovation",
    credit_hrs: 2,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];
