export const mscCourseThreeToSix = [
  {
    code: "CHM655",
    title: "Seminar",
    credit_hrs: 3,
    prerequisite: "",
    semester: "three",
    desc: "",
  },
  {
    code: "CHM656",
    title: "Thesis",
    credit_hrs: 12,
    prerequisite: "",
    semester: "three",
    desc: "",
  },
];

// Analytical Chemistry
export const analyticalMscCourseOne = [
  {
    code: "CHM611",
    title: "Advanced Research Methodology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM612",
    title: "Chemistry of Life Processes",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM613",
    title: "Advances in Analytical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM614",
    title: "Air, and Soil Analyses",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM615",
    title: "Food and Water Analysis Elective",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM616*",
    title: "Environmental Economics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM616*",
    title: "Application of Geochemical Technology in Petroleum Exploration",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM618*",
    title: "Advanced Mineral Processing and Metallurgy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];

export const analyticalMscCourseTwo = [
  {
    code: "CHM621",
    title: "Quality Assurance of Chemical Products/Products Export Criteria",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM622",
    title: " Electronics and Instrumentation",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM623",
    title: "Forensic Chemistry and Toxicology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM624",
    title: "Process Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM625",
    title: "Advanced Theoretical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM626*",
    title: "Textile and Colour Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM626*",
    title: "Advanced Wood Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

// Environmental Chemistry
export const environmentalMscCourseOne = [
  {
    code: "CHM611",
    title: "Advanced Research Methodology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM612",
    title: "Chemistry of Life Processes",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "CHM614",
    title: "Air, and Soil Analyses",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM615",
    title: "Food and Water Analysis Elective",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM619",
    title: "Organic Photochemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM616*",
    title: "Environmental Economics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM616*",
    title: "Application of Geochemical Technology in Petroleum Exploration",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM618*",
    title: "Advanced Mineral Processing and Metallurgy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];
export const environmentalMscCourseTwo = [
  {
    code: "CHM621",
    title: "Quality Assurance of Chemical Products/Products Export Criteria",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM622",
    title: "Electronics and Instrumentation",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM628",
    title: "Advances in Energy Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM629",
    title: "Advances in Pollution Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM625*",
    title: "Advances in Theoretical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM626*",
    title: "Textile and Colour Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM626*",
    title: "Advanced Wood Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

//  Industrial Chemistry
export const industrialMscCourseOne = [
  {
    code: "CHM611",
    title: "Advanced Research Methodology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM612",
    title: "Chemistry of Life Processes",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "CHM631",
    title: "Food Chemistry and Technology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM632",
    title: "Process Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM619",
    title: "Organic Photochemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM616*",
    title: "Environmental Economics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM618*",
    title: "Advanced Mineral Processing and Metallurgy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM633*",
    title: "Advanced Paper Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];
export const industrialMscCourseTwo = [
  {
    code: "CHM621",
    title: "Quality Assurance of Chemical Products/Products Export Criteria",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM622",
    title: "Electronics and Instrumentation",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM624",
    title: "Advances in Industrial Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM629",
    title: "Advances in Pollution Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM625*",
    title: "Advances in Theoretical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM626*",
    title: "Textile and Colour Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM626*",
    title: "Advanced Wood Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

//  Inorganic Chemistry
export const inorganicMscCourseOne = [
  {
    code: "CHM611",
    title: "Advanced Research Methodology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM612",
    title: "Chemistry of Life Processes",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "CHM634",
    title: "Molecular Polyhedral Compounds",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM635",
    title: "Advancement in Coordination Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM636",
    title: "Medicinal Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM616*",
    title: "Environmental Economics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM616*",
    title: "Application of Geochemical Technology in Petroleum Exploration",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM618*",
    title: "Advanced Mineral Processing and Metallurgy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];
export const inorganicMscCourseTwo = [
  {
    code: "CHM622",
    title: "Electronics and Instrumentation",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM641",
    title: "Advanced Chemistry of Inner Transition Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM642",
    title: "Special Topics in Inorganic Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM643",
    title: "Homogeneous and Heterogeneous Catalysis",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM625*",
    title: "Advances in Theoretical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM626*",
    title: "Textile and Colour Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM626*",
    title: "Advanced Wood Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

//  Organic Chemistry
export const organicMscCourseOne = [
  {
    code: "CHM611",
    title: "Advanced Research Methodology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM612",
    title: "Chemistry of Life Processes",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "CHM636",
    title: "Medicinal Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM636",
    title: "Advanced Organic Spectroscopy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM619",
    title: "Organic Photochemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM616*",
    title: "Environmental Economics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM616*",
    title: "Application of Geochemical Technology in Petroleum Exploration",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM618*",
    title: "Advanced Mineral Processing and Metallurgy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];

export const organicMscCourseTwo = [
  {
    code: "CHM622",
    title: "Electronics and Instrumentation",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM644",
    title: "Bioorganic Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM645",
    title: "Industrial Organic Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },

  {
    code: "CHM646",
    title: "Drug Discovery and Development",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM625*",
    title: "Advances in Theoretical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM626*",
    title: "Textile and Colour Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM626*",
    title: "Advanced Wood Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

//  Physical Chemistry
export const physicalMscCourseOne = [
  {
    code: "CHM611",
    title: "Advanced Research Methodology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM612",
    title: "Chemistry of Life Processes",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "CHM638",
    title:
      "Advances in Electro-Catalysis/Semi Conducting Oxides and Nano-Materials",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM639",
    title: "Advances in Chemical Thermodynamics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM651",
    title: "Biophysical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM616*",
    title: "Environmental Economics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM616*",
    title: "Application of Geochemical Technology in Petroleum Exploration",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM618*",
    title: "Advanced Mineral Processing and Metallurgy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];

export const physicalMscCourseTwo = [
  {
    code: "CHM621",
    title: "Quality Assurance of Chemical Products/Products Export Criteria",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM622",
    title: "Electronics and Instrumentation",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM646",
    title: "Advances in Electrochemistry and Electrochemical Technology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM648",
    title:
      "Advances in Stress Corrosion/Hydrogen Embrittlement in Petroleum Industry etc",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM625*",
    title: "Advanced Theoretical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM626*",
    title: "Textile and Colour Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM626*",
    title: "Advanced Wood Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];

//  Polymer Chemistry
export const polymerMscCourseOne = [
  {
    code: "CHM611",
    title: "Advanced Research Methodology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM612",
    title: "Chemistry of Life Processes",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },

  {
    code: "CHM652",
    title: "Advanced Polymer Synthesis",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM653",
    title: "Plastic Equipment and Plant Design",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM654",
    title: "Advanced Polymer Processing Technology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM616*",
    title: "Environmental Economics",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM616*",
    title: "Application of Geochemical Technology in Petroleum Exploration",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
  {
    code: "CHM618*",
    title: "Advanced Mineral Processing and Metallurgy",
    credit_hrs: 3,
    prerequisite: "",
    semester: "first",
    desc: "",
  },
];

export const polymerMscCourseTwo = [
  {
    code: "CHM622",
    title: "Electronics and Instrumentation",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM649",
    title: "Polymer Reactor Engineering",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM661",
    title: "Solid State Properties of Polymer",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },

  {
    code: "CHM662",
    title: "Polymer Rheology",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM625*",
    title: "Advanced Theoretical Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM626*",
    title: "Textile and Colour Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
  {
    code: "CHM633*",
    title: "Advanced Paper Chemistry",
    credit_hrs: 3,
    prerequisite: "",
    semester: "second",
    desc: "",
  },
];
