export const publications = [
  {
    title:
      "CHEMICAL COMPOSITION AND BIOLOGICAL ACTIVITIES OF Uvaria chamae SEED OIL",
    unit: "organic",
    author: "Oduduatta Essien EKANEM",
    supervisor: "",
    type: "msc",
    published_at: "JUNE 2023",
    desc: `Plants contain a reservoir of phytochemicals which are responsible for the treatment of several diseases including oxidative stress related diseases among others. Oxidative stress stems from an imbalance between the production and accumulation of oxidant species and a biological system's ability to readily detoxify the reactive intermediates (radicals) or easily restore the resulting damage. This poses severe injury to cellular systems and threatens an organism's health, leading to many chronic diseases such as diabetes, cancer, hypertension, ageing, Alzheimer's disease, and cardiovascular diseases. Other effect due to oxidative stress damage include atherosclerosis, rheumatoid arthritis, post-ischemic perfusion injury, myocardial infarction, chronic inflammation, stroke and septic shock, ageing and other degenerative diseases in humans. To counter this decay, researchers have now sought antioxidants of plant origin and have reported their potential against reactive oxygen species.`,
    href: "https://drive.google.com/file/d/1vARXNUt5UURcsrmi-NSEtxiIUDQh5KrC/view",
  },
  {
    title:
      "EVALUATION OF THE PROPERTIES OF Luffa cylindrica (SPONGE GOURD) FRUIT FIBRE AND Zea mays (MAIZE) HUSK AS POTENTIAL BIOPLASTICS RAW MATERIALS",
    unit: "environmental",
    author: "Roland Nzan OGAR",
    supervisor: "",
    type: "msc",
    published_at: "JULY 2023",
    desc: `There has been an increase in the requirements for plastics because of its cost effectiveness, lighter weight compared to other materials such as metals and ceramics, waterproof nature, and strength. In addition to these advantages, plastics exhibit disadvantages of difficulty in rapid decomposition and non-renewability, possibly leading to environmental pollution. A general solution to solve this issue involves the use of biodegradable polymers as the main ingredient in preparing plastics; Cellulose can be the main choice as raw materials for making bioplastics because the source of cellulose can be obtained from waste so that it can also be a solution to overcome environmental problems.`,
    href: "https://drive.google.com/file/d/1vC0jFgQq4hsg4vDKhVpTQsSeJKlo26cT/view",
  },
  {
    title:
      "TRIPARTITE MAGNETIC MONTMORILLONITE NANOCOMPOSITE FOR REMOVAL OF BISPHENOL A, NICKEL, CADMIUM AND LEAD IONS FROM INDUSTRIAL EFFLUENTS",
    unit: "environmental",
    author: "Okon Edem OKON",
    supervisor: "",
    type: "msc",
    published_at: "JULY 2023",
    desc: `The removal of Bisphenol A. Ni, Cd and Pb ions onto unmodified montmorillonite (MM), doped titanium nanocomposite (DTC) and tripartite magnetic montmorillonite nanocomposite (TMC) was investigated. The nanocomposites were prepared by in-situ reduction with iron salts followed by chemical impregnation by Sol-Gel method and subsequently coupled by chemical precipitation to form the TMC. Relevant spectroscopic methods were also employed for characterization. The modified clays showed magnetic properties with FTIR result, revealing new reflections at 1990 cm for NCS (isocyanate). Similarly, the tripartite magnetic nanocomposite had new reflections at 1032 cm' for cyanide (-OCN), 1625 cm" for open chain azo (-N-N-), and 2050 cm" for transition metal carbonyl (-M-CO-). XRD analysis revealed interlayer spacing (1.67-1.71 nm). BET surface area were respectively 90.39, 210.72 and 288.08 m2/g and adsorption capacities of 81.48, 82.27 and 91.05% for MM, DTC and TMC. The tripartite magnetic composite also had higher adsorption and photodegradation capacity (96.21%) towards the organic pollutant compared to unmodified clay (22.99% ). Adsorption data were best fitted with Freundlich isotherm model revealing multilayer coverage as predominant mechanism of adsorption. Kinetic mechanism was predominantly pseudo-second-order, revealing chemisorption process. The thermodynamic studies confirmed that the process of adsorption was exothermic and spontaneous with negative standard enthalpy and Gibb's free energy (-58.21 kJ/mol) at 30°C. Similar trends were observed for metal ions adsorption. Modification imparted cationic and aromatic moiety onto the montmorillonite thus increasing pollutant-adsorbent interactions and enhanced adsorption of BPA and metal ions in a simulated industrial effluent. In a continuous plug flow column, the tripartite magnetic composite demonstrated longer breakthrough and exhaustion time (19, 45 hours respectively), compared to the conventional adsorbents (2, 21 and 5, 29 hours respectively) for BPA adsorption from simulated effluent. Similar trend was also observed for real effluent. Adams-Bohart isotherm showed highest adsorption capacity of 120.28 mg/g for simulated effluent and 29.60 mg/g for real effluent. In both real and simulated effluents, bed volume was highest with TMC and revealed that the prepared tripartite nanocomposite is an efficient alternative adsorbent and can compete with commercially available adsorbents.`,
    href: "https://drive.google.com/file/d/1uUDL5LtZ8Y6am7GwODNvBOGNPq-CrhHM/view",
  },
  {
    title:
      "HEALTH RISK ASSESSMENT OF ORGANOCHLORINE PESTICIDES AND TRACE METALS IN WATER, SEDIMENTS AND Papyrocranus afer FROM QUA IBOE RIVER, NIGERIA",
    unit: "organic",
    author: "Nsima Amos AKPAN",
    supervisor: "",
    type: "msc",
    published_at: "AUGUST 2023",
    desc: `Food consumption is an important route of human exposure to organic chemicals. To assess the health risks associated with these chemicals due to fish consumption, the levels of trace metals (Cd, Cr, Ni, Cu, V, Pb, and Sn) and organochlorine pesticides (OCPS) in water and fish (Papyrocranus afer) from Qua Iboe River were assessed using atomic absorption spectrometry (AAS) and gas chromatography-electron capture detector (GC-ECD), respectively. Physicochemical parameters were also determined in water and sediment using standard methods. Levels of the trace metals in water ranged from below detection limit (BDL) to 0.10 mg/L with the trend Cu> Cd > Cr> Ni>V> Sn> Pb. The levels of the trace metals were within WHO and SON acceptable limits. In sediment, the trace metals ranged from 0.01 to 0.21 mg/kg with the same trend. For the fish, the trace metals ranged from BDL to 16.54 mg/kg with the same trend. The GC-ECD analyses of OCPs in the different samples gave variable levels of the OCPS in the investigated samples. The concentrations of the OCPs in the fish ranged from 0.01 to 1.87 ng/g. Significantly, p,p'-DDE in the fish were higher (average 1.87 and 1.82 ng/g for wet and dry seasons respectively) compared with other OCPs. The physicochemical parameters analysis showed variable results in the investigated samples. The estimated risk from trace metals contamination due to consumption of the fish revealed hazard quotient (HQ) values greater than unity, indicating risk in consumption of the fish. The estimated risk in terms of dermal absorption through swimming in the water classified the studied river as unpolluted since HQ values were all less than unity. The estimated risk of OCPs in water and fish revealed the suitability of the water and fish for human consumption at the time of the study. Principal component analysis (PCA) revealed the investigated parameters which exerted influence in the water environment in both seasons. For sustainability of the river for use by the present generation without compromising standard for future generations, routine monitoring of these chemicals in the river is strongly advocated.`,
    href: "https://app.luminpdf.com/viewer/668d65b695ba3898dd01fd89",
  },
  {
    title:
      "CHEMICAL CONSTITUENTS AND PHARMACOLOGICAL ACTIVITIES OF Lasianthera africana LEAVES",
    unit: "organic",
    author: "Desire ThankGod CHRISTOPHER",
    supervisor: "",
    type: "msc",
    published_at: "JUNE 2023",
    desc: `Lasianthera africana is an edible vegetable frequently utilised in major cuisines of Southern Nigeria. The leaves of L. africana (dark glossy leaf variety) have traditional uses for the treatment of various diseases. The leaves of L. africana were evaluated for chemical composition, acute toxicity, anti-inflammatory, antinociceptive, and antioxidant activities using standard procedures. The crude extract was obtained with the use of methanol as extraction solvent; other extracts were successively extracted with solvents of different polarities (dichloromethane, ethyl acetate and methanol). The ethyl acetate extract of L. africana leaves was further purified with vacuum liquid chromatography (VLC) and open column chromatography (CC). Phytochemical screening of the crude methanol extract revealed the presence of saponins and tannins in high concentration; alkaloids, flavonoids, anthraquinones, and cardiac glycosides in moderate amount. The most abundant constituents in the gas chromatography-mass spectrometry of the dichloromethane extract (24 constituents), fixed oils obtained by VLC (46constituents) and CCsub-fractions of the ethyl acetate fraction (17 constituents), were 9-(z) octadecenamide (18.8 %), 1-nonadecene (13.2 %) and hexadecanoic acid, methyl ester (31.5 %), respectively. A median lethal dose (4740 mg/kg) was obtained for the crude methanol extract by oral route using albino mice. In the egg albumin-induced oedema assay, the crude methanol extract demonstrated 64 % oedema inhibition at low dose (474 mg/kg) and 66 % oedema inhibition at high dose (1422 mg/kg). In the acetic acid induced writhing model, the crude methanol extract exhibited 58 % pain inhibition at low dose (474 mg/kg) and 76 % pain inhibition at high dose (1422 mg/kg). The crude methanol extract (100 μg/mL) produced antioxidant activity (absorbance, 1.782) in ferric reducing power assay and also scavenged 90% of diphenyl-1-picrylhyrazyl free radicals. These results indicate that the leaves of L. africana (dark glossy leaf variety) are endowed with good anti-inflammatory, analgesic, and antioxidant constituents that deserve further purification to isolate the bioactive compounds.`,
    href: "https://drive.google.com/file/d/1y1KnXc3wuPe1d4kNdzm-FW_wO98Cciow/view",
  },

  // new
  {
    title:
      "Isolation, Characterisation and Corrosion Inhibitory Potentials of Extracts from the Seeds of Cola nitida on Mild Steel in Hydrochloric Acid Solution",
    unit: "physical",
    author: "Mboso Isaac OBODOM",
    supervisor: "Dr Inemesit A. Akpan",
    type: "phd",
    published_at: "APRIL 2024",
    desc: `Mature seeds of Cola nitida were subjected to extraction using dichloromethane (DCM). The extract was concentrated and put through vacuum liquid, column and thin layer chromatographic processes. Three pure compounds were isolated, characterised using FT-IR, H-NMR, C-NMR and DEPT-135 and identified as 1, 3, 5-trimethoxymethylbenzene (TMMB), 1, 3-dimethyl-7H-purine-2, 6-dione (DMPD) and 1, 3, 7-trimethylpurine-2, 6-dione (TMPD). Two semi-pure compounds were also isolated and coded Mb4 and Mb5. Corrosion inhibition of mild steel in 1 M HCI with different concentrations of the isolates was investigated using weight loss and electrochemical methods. Computational studies and scanning electron microscopy were also carried out. Weight loss results revealed that corrosion inhibition efficiencies at 303 K and at 5.0 x10 gL concentration of the inhibitors followed the order: Mb4 (80.82%) > TMPD (72.08%) > Mb5 (69.17%) > DMPD (65.83%) > TMMB (55.83%). Corrosion inhibition efficiencies obtained from electrochemical methods and computational studies had similar trend. Based on the values of AGads at 303 K and at 5.0 X10gL [TMMB (-22.45 kJ mol"), DMPD (-17.74 kJ mol), TMPD (17.46 kJ mol), Mb4 (22.47 kJ mol) and Mb5 (-92.52 kJ mol)] and the values of AHads at 303 K and at 5.0 x gL [TMMB (38.47 kJ mol1), DMPD (36.84 kJ mol'), TMPD (36.69 kJ mol1), Mb4 (51.79 kJ mol) and Mb5 (34.06 kJ mol)], the adsorption process of the inhibitors onto the surface of mild steel was spontaneous and endothermic. Adsorption of the inhibitors fitted to Temkin isotherm. Decrease in corrosion inhibition efficiencies with increase in temperature favoured physical adsorption phenomenon. Some of the quantum chemical parameters of the isolates obtained were EHOMO: TMMB (-6.570 eV), DMPD (-6.079 eV) and TMPD (-6.033 eV), energy gap (AE): TMMB (6.248 eV), DMPD (5.181 eV) and TMPD (5.163 eV) and electronegativity (7): TMMB (3.446 eV), DMPD (3.507 eV) and TMPD (3.545 eV). These values are lower than the work function of Fe(110) which is 4.82 eVand this implies that electrons migrate from inhibitors to the steel. EHOMO projects corrosion inhibitory potential and high values reflect better inhibition. AE is a reactivity factor and its low value results in good inhibition. Interaction energy obtained from molecular dynamic simulation of the inhibitors on Fe(110) plane at 303 K were in the order: DMPD (-105.918 kcal mol"')> TMPD (-114.46 kcal mol"')> TMMB (-130.9 kcal mol1). Interaction energy represents the binding energy of the adsorbate on the adsorbent. Micrographs of scanning electron microscopy (SEM) revealed the formation of dense film on the surface of mild steel which retarded the activities of aggressive ions. Therefore, it is concluded that isolates from C. nitida are effective green corrosion inhibitors of mild steel in hydrochloric acid solution.`,
    href: "/chem-research/cola_nitida.pdf",
  },
  {
    title:
      "Preparation, Characterization and Application of Lignin and Lignin Esters from Gmelina wood as Bioadsorbent for the Treatment of Gold Mining Effluents",
    unit: "organic",
    author: "Aniekan Effiong AKPAKPAN",
    supervisor: "Prof. Ukama D. Akpabio",
    type: "phd",
    published_at: "MARCH 2023",
    desc: `Lignin is a non-carbohydrate major component of wood usually released in large quantity as a waste material during wood pulping. In this research, lignin was extracted from Gmelina arborea wood using Soda and Kraft pulping processes. It was modified into lignin esters using succinic and maleic anhydride respectively. Lignin, succinylated Kraft lignin (SKL), maleated Kraft lignin (MKL), succinylated Soda lignin (SSL) and maleated Soda lignin (MSL) were characterized using Fourier Transformed Infrared Spectroscopy (FTIR), UV/visible spectrophotometer, Scanning Electron Microscope (SEM), Electrospray Ionization-Mass Spectroscopy (ESI-MS) and potentiometric titration. These bioadsorbents were applied in the adsorption of Pb2+ and Cd2+ from simulated mining effluent. Effect of contact time (30-150 min), adsorbent dosage (50-250 mg), adsorbate concentration (10 - 50 mg/L), adsorbate pH (2-6), isotherm and kinetics models of each adsorption process were evaluated. The results were analyzed using independent t-test at a < 0.05. The bioadsorbents were also applied in the adsorption of Pb2+, Cd2+, As2+, Au2+ and Hg2+ from gold mining effluents obtained from Osun State. FTIR results of lignins and their ester derivatives showed a broad absorption band of free hydroxyl group at 3500 - 3000 cm. Lignin esters showed a carbonyl peak at 1710 -1703 cm31. Maleated derivatives showed a carbon carbon double bond peaks at 1648 - 1630 cm1. UV/visible spectroscopy results revealed a bathochromic shift and hypochromic effect in Kraft lignin derivatives and hypsochromic shift in Soda lignin derivatives. Hypochromic and hyperchromic effects occurred in SSL and MSL respectively. ESI-MS spectra revealed that lignin monomers were higher in Kraft lignin while dimers were higher in the Soda lignin. The surface morphology of all the bioadsorbents were heterogeneous. Potentiometric titration indicated a surface area ranges from 45.40 - 399.00 m2/g. In all the adsorption processes, adsorption efficiency increased with increase in adsorbent dosage, contact time and pH, but decreased with increase in the adsorbate concentration. Most of the adsorption processes followed Langmuir isotherm and second order kinetics. Statistical analysis revealed a significant difference in the adsorption efficiency of lignin and its ester derivatives. Also, there was no significant difference in the adsorption in single metal and binary metal systems. However, lignin esters adsorbed over 80% of the heavy metals in simulated effluents and over 60% in the gold mining effluents. The results indicate that lignin which is presently discarded as waste material could be modified into lignin esters and applied as bioadsorbent in the adsorption of heavy metals from gold mining effluent.`,
    href: "/chem-research/lignin.pdf",
  },
  {
    title: "",
    unit: "",
    author: "organic",
    supervisor: "",
    type: "phd",
    published_at: "APRIL 2023",
    desc: `Comparative study of physicochemical characteristics of Oil Palm Empty Fruit Bunch (OPEFB) and Oil Palm Mesocarp Fibre (OPMF) was carried out, pulping, bleaching and paper making were done according to Technical Association of Pulp and Paper Industries (TAPPI) Standards of USA. The results obtained showed that the chemical components of Oil Palm Empty Fruit Bunchand Oil Palm Mesocarp Fibre were: moisture content (21%, 18%); ash content (9.12%, 4.55%); lignin (16.15%, 18.65%); cellulose (44.56%, 42.22%); hemicelluloses (31.24%, 31.85%) respectively. The solubility in cold water (8.32%, 8.76%); hot water (15.16%, 19.12%); 1% NaOH (33.75%, 34.15%); 18% NaOH (38.65%, 40.85%); and 2:1 ethanol-benzene (20.51%, 27.38%) were obtained respectively. The fibre dimensionsdetermined by digital camera microscope, Model XSZ, 2003 were: fibre length (0.95, 0.86) mm; fibre diameter (13.66, 12.35) μm; fibre width (5.82, 5.31) μm; cell wall thickness (3.42, 3.09) μm; Runkel ratio (1.0, 1.0); and flexibility coefficient (0.50,0.50) respectively. The yields of the unbleached pulp of OPEFB and OPMF were 40.52% and 34.86% while the bleached pulps were 57.35% and 47.33% respectively, and the residual lignin expressed as Kappa number were 50% and 60% respectively. The sheets formed from the pulps had good formation but with low tensile - tear strength of (0.01N/m, 0.01N/m); thus, these pulps belong to short fibre class which implies that they should be blended with other long fibre pulpsto produce strong customized sheets for different applications.`,
    href: "/chem-research/oil_pam.pdf",
  },
  {
    title: "",
    unit: "",
    author: "",
    supervisor: "",
    type: "phd",
    published_at: "JUNE 2023",
    desc: ``,
    href: "/chem-research/polychlorinated_biphenyls.pdf",
  },
  {
    title: "",
    unit: "",
    author: "",
    supervisor: "",
    type: "phd",
    published_at: "JUNE 2023",
    desc: ``,
    href: "/chem-research/surface_water.pdf",
  },
];
