export const journalInfo = [
  {
    title: "journal of chemicals",
    author: "prof. peter monk",
    published_at: "21-02-2022",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: "research",
  },
  {
    title: "journal of chemicals",
    author: "prof. peter monk",
    published_at: "21-02-2022",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: "research",
  },
  {
    title: "journal of chemicals",
    author: "prof. peter monk",
    published_at: "21-02-2022",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: "research",
  },
  {
    title: "journal of chemicals",
    author: "prof. peter monk",
    published_at: "21-02-2022",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: "research",
  },
  {
    title: "journal of chemicals",
    author: "prof. peter monk",
    published_at: "21-02-2022",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: "research",
  },
  {
    title: "journal of chemicals action of detergent",
    author: "Dr. edet uno",
    published_at: "21-05-2021",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: "research",
  },
  {
    title: "journal of xenobiotics",
    author: "Mr. mark akpan",
    published_at: "01-09-2020",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: "research",
  },
];

export const articleInfo = [
  {
    title: "article of chemicals",
    author: "prof. peter monk",
    published_at: "21-02-2022",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: "research",
  },
  {
    title: "article of chemicals action of detergent",
    author: "Dr. edet uno",
    published_at: "21-05-2021",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: "research",
  },
  {
    title: "article of xenobiotics",
    author: "Mr. mark akpan",
    published_at: "01-09-2020",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: "research",
  },
];

export const publications = [
  {
    title:
      "Effect of consumption of goat dehaired with scrap tyre fire on some hematological indices of albino wistar rats",
    unit: "physical",
    author: "Clever Solomon Akanimoh",
    published_at: "13-11-2023",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: undefined,
  },
  {
    title: "Antimicrobial activity of cinnamomun tamala",
    unit: "analytical",
    author: "Akpan, Iniobong Samuel",
    published_at: "13-11-2023",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: undefined,
  },
  {
    title:
      "Effect of consumption of goat dehaired with scrap tyre fire on some growth indices of albino wistar rats",
    unit: "organic",
    author: "Evelyn Akpan Joe",
    published_at: "30-11-2023",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: undefined,
  },
  {
    title: "Toxins in diets prepared using goat dehaired with scrap tyre fire",
    unit: "physical",
    author: "akai tommy eze",
    published_at: "05-01-2023",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: undefined,
  },
  {
    title: "Toxins in diets prepared using goat dehaired with scrap tyre fire",
    unit: "inorganic",
    author: "Moses Mark Monday",
    published_at: "05-01-2023",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: undefined,
  },
  {
    title:
      "Effect of consumption of goat dehaired with scrap tyre fire on the hematological indices of albino wistar rats",
    unit: "analytical",
    author: "Clever Solomon Akanimoh",
    published_at: "13-11-2023",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: undefined,
  },
  {
    title: "Toxins in diets prepared using goat dehaired with scrap tyre fire",
    unit: "environmental",
    author: "Moses Mark Monday",
    published_at: "05-01-2023",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: undefined,
  },
  {
    title:
      "Effect of consumption of goat dehaired with scrap tyre fire on the hematological indices of albino wistar rats",
    unit: "organic",
    author: "Clever Solomon Akanimoh",
    published_at: "13-11-2023",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: undefined,
  },
  {
    title: "Toxins in diets prepared using goat dehaired with scrap tyre fire",
    unit: "environmental",
    author: "Moses Mark Monday",
    published_at: "05-01-2023",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: undefined,
  },
  {
    title: "Toxins in diets prepared using goat dehaired with scrap tyre fire",
    unit: "physical",
    author: "Moses Mark Monday",
    published_at: "05-01-2023",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: undefined,
  },
  {
    title: "Antimicrobial activity of cinnamomun tamala",
    unit: "inorganic",
    author: "Sampson Michael Ekpo",
    published_at: "13-11-2023",
    desc: "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Nesciunt ab necessitatibus officiis et labore sapiente voluptatum deserunt! Magni atque minima quis itaque maxime quos soluta earum, quae optio quas ad.",
    href: undefined,
  },
];
